# Generated by Django 2.1.7 on 2019-06-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Photo', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=50)),
                ('Flag', models.CharField(max_length=100)),
                ('Overall', models.IntegerField()),
                ('Potential', models.IntegerField()),
                ('Club', models.CharField(max_length=50)),
                ('ClubLogo', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=10)),
                ('Wage', models.CharField(max_length=10)),
                ('PreferredFoot', models.CharField(max_length=10)),
                ('Position', models.CharField(max_length=10)),
                ('Height', models.CharField(max_length=10)),
                ('Weight', models.CharField(max_length=10)),
                ('Finishing', models.IntegerField()),
                ('HeadingAccuracy', models.IntegerField()),
                ('ShortPassing', models.IntegerField()),
                ('Volleys', models.IntegerField()),
                ('Dribbling', models.IntegerField()),
                ('Curve', models.IntegerField()),
                ('FKAccuracy', models.IntegerField()),
                ('LongPassing', models.IntegerField()),
                ('BallControl', models.IntegerField()),
                ('Acceleration', models.IntegerField()),
                ('SprintSpeed', models.IntegerField()),
                ('Agility', models.IntegerField()),
                ('Reactions', models.IntegerField()),
                ('Balance', models.IntegerField()),
                ('ShotPower', models.IntegerField()),
                ('Jumping', models.IntegerField()),
                ('Stamina', models.IntegerField()),
                ('Strength', models.IntegerField()),
                ('LongShots', models.IntegerField()),
                ('Aggression', models.IntegerField()),
                ('Interceptions', models.IntegerField()),
                ('Positioning', models.IntegerField()),
                ('Vision', models.IntegerField()),
                ('Penalties', models.IntegerField()),
                ('Marking', models.IntegerField()),
            ],
        ),
    ]
